### PR TITLE
Added multiple disco scenarios

### PR DESCRIPTION
**Pull request by pschuette-iloan**
Added scenarios for output

@stevenskim - What else should be in here?

### CODE REVIEW

**Comment by pschuette-iloan** [comment]
@himankarbn - How are we looking on this?

**Review by himankarbn — APPROVED** [review]
LGTM 👍

**Comment by himankarbn** [comment]
@pschuette-iloan : I think it will be good to move this repo under springleaf?

**Comment by pschuette-iloan** [comment]
@himankarbn  - Not sure how to do that, tbh

**Pull request merged**
